# Project Name: Aixt, https://github.com/fermarsan/aixt.git
#  File Name: setup.toml (CH552 Core Board)
#  Author: Fernando M. Santa
#  Date: 2023
#  License: MIT
#
#  Description: This is the setup file for the CH552 Core Board version of Aixt project

device =  "CH552"
board =   "CH552 Core Board"

backend = "arduino"

cc_linux =      "ardu"
cc_windows =    "c:\\v\\thirdparty\\ardu.exe"
#  cc_flags = ["-0" ]

i8 =    "signed char"
i16 =   "short"
i32 =   "long"
i64 =   "long long"
isize = "long long"
int =   "long"

u8 =    "unsigned char"
u16 =   "unsigned short"
u32 =   "unsigned long"
u64 =   "unsigned long long"
usize = "unsigned long long"

f32 =   "float"
f64 =   "double"

default_int =   "int"
default_float = "float"

mutex = "NOT SUPPORTED"
main_ret_type = "int"
main_params =   "none"   

api_modules =   []
  
headers =   []

macros =    []

config_operator =   []

configuration = []

initialization =    []